# Generated by Django 2.0.6 on 2018-06-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20180629_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_forum',
            name='author',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='message_forum',
            name='content',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='message_forum',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
