# Generated by Django 2.0.6 on 2018-06-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20180629_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_forum',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
